# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=6)),
                ('tax_only', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile_objects', to=settings.AUTH_USER_MODEL)),
                ('current_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_shop', to='shops.Shop')),
                ('shops', models.ManyToManyField(blank=True, related_name='user_shops', to='shops.Shop')),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_profile_objects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
                'db_table': 'user_profile',
                'verbose_name': 'user_profile',
                'verbose_name_plural': 'user_profiles',
            },
        ),
    ]
