# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20170712_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproduct',
            old_name='input_tax',
            new_name='input_gst',
        ),
    ]
