# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_cheque',
            field=models.BooleanField(default=False),
        ),
    ]
