# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('shop_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128)),
                ('contact_no', models.CharField(max_length=128)),
                ('tin', models.CharField(blank=True, max_length=128, null=True)),
                ('cst', models.CharField(blank=True, max_length=128, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_shop_objects', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_shop_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('shop_id',),
                'db_table': 'shops_shop',
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
    ]
