# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cst',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
