# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_cst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tin',
            new_name='gstin',
        ),
    ]
