# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170713_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('intra_state', 'Intra State'), ('inter_state', 'Inter State')], default='intra_state', max_length=128),
        ),
    ]
